docs: update readme
antvis/color-schema pull request #17
Opened 2021-06-03 08:24 UTC by cxxxxxn

2021-06-03 14:36 UTC, neoddish requested changes
readme 还需要有个中文版，记得吗~

2021-06-03 14:36 UTC, neoddish commented on README.md
> +          usage: "danger"
shall we have multi usages? maybe `usage` could be an array

2021-06-03 14:36 UTC, neoddish commented on README.md
> +          },
```suggestion
          { space: "hex", value: "#8B59FF" },
```

2021-06-04 08:17 UTC, cxxxxxn commented on src/schema/colorValue.ts
> +export type ColorSpace = "hex" | "hsl" | "hsv" | "hsi" | "rgb" | "rgba" | "lab" | "lch" | "cmyk";
hex感觉更像是一种表示形式（可以表示rgb和rgba）而不是color space哦
https://gka.github.io/chroma.js/#color-hex

2021-06-05 10:21 UTC, neoddish commented on src/schema/colorValue.ts
> +export type ColorSpace = "hex" | "hsl" | "hsv" | "hsi" | "rgb" | "rgba" | "lab" | "lch" | "cmyk";
Good point! 如何在类型上进行修改？

2021-06-07 03:07 UTC, cxxxxxn commented on src/schema/colorValue.ts
> +export type ColorSpace = "hex" | "hsl" | "hsv" | "hsi" | "rgb" | "rgba" | "lab" | "lch" | "cmyk";
hex应该要从colorSpace中移除。
那是否需要加上一个属性叫format（除了hex，可能还有object，name，number之类的）。从实现上考虑的话，可以先不用吧，上面提及的类型可以用代码判断出来。

2021-06-07 10:12 UTC, neoddish approved these changes
LGTM

TODO： remove hex

2021-06-07 10:13 UTC, merged